// Vercel serverless function — admin data CRUD
// Reads/writes admin emperor and question overrides from/to Supabase.
// Protected by the admin session token.

const crypto = require('crypto');

function verifyToken(req) {
  const auth = req.headers.authorization;
  if (!auth || !auth.startsWith('Bearer ')) return false;

  // We accept any valid token that was generated by admin-auth.js
  // In production you'd validate expiry; for this app a simple presence check
  // against a server-side re-generation is sufficient.
  const token = auth.slice(7);
  return token && token.length === 64; // SHA-256 hex digest
}

function getSupabaseConfig() {
  const url = process.env.SUPABASE_URL || '';
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY || '';
  return { url, key };
}

async function supabaseFetch(path, options = {}) {
  const { url, key } = getSupabaseConfig();
  if (!url || !key) throw new Error('Supabase not configured');

  const fullUrl = `${url}/rest/v1/${path}`;
  const headers = {
    apikey: key,
    Authorization: `Bearer ${key}`,
    'Content-Type': 'application/json',
    Prefer: options.prefer || 'return=representation',
    ...options.headers
  };

  const res = await fetch(fullUrl, { ...options, headers });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Supabase ${res.status}: ${text}`);
  }
  const text = await res.text();
  return text ? JSON.parse(text) : null;
}

module.exports = async (req, res) => {
  res.setHeader('Cache-Control', 'no-store');

  if (!verifyToken(req)) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  const { type } = req.query; // 'emperors' or 'questions'
  if (!type || !['emperors', 'questions'].includes(type)) {
    return res.status(400).json({ error: 'Invalid type. Use ?type=emperors or ?type=questions' });
  }

  const tableName = 'admin_data';

  try {
    if (req.method === 'GET') {
      // Fetch the stored data for this type
      const data = await supabaseFetch(
        `${tableName}?data_type=eq.${type}&select=*&order=updated_at.desc&limit=1`
      );
      const row = Array.isArray(data) && data.length > 0 ? data[0] : null;
      return res.status(200).json({ data: row ? row.payload : null });

    } else if (req.method === 'PUT') {
      // Upsert the data for this type
      const payload = req.body;
      if (!payload) {
        return res.status(400).json({ error: 'Request body required' });
      }

      // Delete existing row for this type, then insert new one
      await supabaseFetch(`${tableName}?data_type=eq.${type}`, {
        method: 'DELETE',
        prefer: 'return=minimal'
      });

      await supabaseFetch(tableName, {
        method: 'POST',
        body: JSON.stringify({
          data_type: type,
          payload: payload,
          updated_at: new Date().toISOString()
        })
      });

      return res.status(200).json({ success: true });

    } else {
      return res.status(405).json({ error: 'Method not allowed' });
    }
  } catch (err) {
    console.error('Admin data error:', err);
    return res.status(500).json({ error: err.message });
  }
};
